### ISSUE TITLE
having issue with react-native

### ISSUE THREAD

**Issue by pkrinesh** [InfiniteXyy/zoov#6] opened 2023-02-08 15:11 UTC
zoov worked just fine with react but when i tried to use in react-native with expo managed flow. I am getting "TypeError: Object is not a function". I am sharing expo-snack link you can check. [https://snack.expo.dev/@krinesh/zoov-demo](https://snack.expo.dev/@krinesh/zoov-demo). 

Is zoov is not compatible with react-native or am i missing something here?

**Comment by InfiniteXyy** [comment] 2023-02-09 04:26
It's caused by the react-native bundle incompatibility.

Should be fixed in v0.5.2, would you mind check it?

**Comment by pkrinesh** [comment] 2023-02-09 07:15
Cool. It is working just fine. 

I have updated the expo-snack to v0.5.2. [zoov-react-native-snack](https://snack.expo.dev/@krinesh/zoov-demo)

**Comment by pkrinesh** [comment] 2023-02-09 08:01
Hi

While using useuseTrackedModule with react-native getting an "Unable to resolve module zoov/tracked" error.

**Comment by InfiniteXyy** [comment] 2023-02-10 03:00
Thanks for your feedback!

I refactored the publish folder structure, to make it compatible with `webpack`  v4, and `metro` bundler. release in 0.5.3

Feel free to add some comment, if there is some other issues I didn't cover.

BTW, remember to install `react-tracked`, it's a essential dependency if you want to use `useTrackedModule`

**Comment by pkrinesh** [comment] 2023-02-10 07:14
Thanks for your fast response! and great work by the way.

Now it is working just fine and  I am leaving it open for now.

**Closed as completed** 2023-07-01 01:27 UTC
